### ISSUE TITLE
Transient annotation for lazy logging

### ISSUE THREAD

**Issue by eshu** [lightbend/scala-logging#104]
Please, add @transient annotation here:

https://github.com/typesafehub/scala-logging/blob/c8066a7aee6e11265c8d49d6fce9960c92d189ea/src/main/scala/com/typesafe/scalalogging/Logging.scala#L27

The reason was explained here: https://www.mail-archive.com/user@spark.apache.org/msg29010.html

**Comment by dbast** [comment]
This is not required according to #84

**Comment by Atry** [comment]
Not required but it is still good to have.

Fixed in #114
