### ISSUE TITLE
relocate to different GitHub org?

### ISSUE THREAD

**Issue by SethTisue** [lightbend/scala-logging#110]
in general, we're aiming for https://github.com/typesafehub to consist only of archived/abandoned repos

often we are relocating repos from https://github.com/typesafehub to https://github.com/lightbend . but although this repo started at Typesafe, it's not really official Lightbend stuff anymore (I don't think? right?)

would it make sense to make a new org to put it under...? or relocate it to the current maintainer's personal org?

**Comment by analytically** [comment]
Happy to relocate under lightbend.

**Comment by SethTisue** [comment]
okay, let's just relocate to lightbend org, then. @ktoso do you have the requisite superpowers?

**Comment by ktoso** [comment]
I do, will move today. Will check if I can give superpowers to you as well

**Comment by ktoso** [comment]
Repo moved, please let me know if anyone lost permissions in the process so I can re-add them, but I think everything should be fine

**Comment by SethTisue** [comment]
thanks Konrad!
