### ISSUE TITLE
LoggerTakingImplicit is missing

### ISSUE THREAD

**Issue by klpx** [lightbend/scala-logging#113]
Hi! I found your cool library and noticed implicit context capture feature.
But when I add it to my build.sbt:
```scala
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging" % "3.7.2"
```
i dont see method `takingImplicit` in `com.typesafe.scalalogging.Logger`
Also, there is no such method in generated docs: https://www.javadoc.io/doc/com.typesafe.scala-logging/scala-logging_2.12/3.7.2

**Comment by klpx** [comment]
![image](https://user-images.githubusercontent.com/2909427/35950522-051e1724-0c88-11e8-8151-c58e340792ce.png)

**Comment by Atry** [comment]
It seems not released yet.

**Comment by Atry** [comment]
Hi @analytically, is there a plan to release scala-logging 3.8.0 ?

**Comment by analytically** [comment]
No plan yet, would you be able to open PR's for your comments?

**Comment by klpx** [comment]
Oh. I just looked at README and it references to "3.7.2". Ok. thanks!

**Comment by analytically** [comment]
3.8.0 is out now.
