### ISSUE TITLE
Logger macro automatically includes line number or file name and line number

### ISSUE THREAD

**Issue by JohnReedLOL** [lightbend/scala-logging#126]
I understand that the scala-logging is a macro that wraps log-4-j Can I get a feature where this logger sticks the line number into the log statements so that they are easier to find in the source code? Something like this:

logger.debug("foo")

Gets converted to:

logger.debug("foo" + " - MyFile:43")

Or at the very least if you won't implement it can you point me to where in the source code I should go to make this change myself? Thx.

**Comment by analytically** [comment]
Happy to consider a PR. Check out the classes here: https://github.com/lightbend/scala-logging/tree/master/src/main/scala/com/typesafe/scalalogging
