### ISSUE TITLE
Publish for 2.13.0-M4

### ISSUE THREAD

**Issue by Lasering** [lightbend/scala-logging#127]
It seems the CI already passed all the tests for 2.13.0-M4. Could this be released?

Its the only dependency preventing me from testing against 2.13.0-M4.

**Comment by SethTisue** [comment]
@analytically? (can I be of any assistance here...?)

**Comment by analytically** [comment]
Published :-)

**Comment by analytically** [comment]
(only 3.9.0 is available for 2.13.0-M4)
