### ISSUE TITLE
Add marker variable to is*Enabled macros

### ISSUE THREAD

**Issue by balatbn** [lightbend/scala-logging#139]
Currently the macro code in LoggerMacro doesn't pass marker as parameter. All the is*Enabled methods do take marker as a value.

We want to control the logging level depending on marker value. Since marker is not passed to is*Enabled method, in our TurboFilters we are not able to make that decision.

**Comment by eugeniyk** [comment]
Just faced with same issue, change should be trivial, testing may be harder
