### ISSUE TITLE
missing 3.9.2 tag on GitHub

### ISSUE THREAD

**Issue by xuwei-k** [lightbend/scala-logging#143]

**Comment by francisdb** [comment]
Also the version on master should be 2.9.3-SNAPSHOT

**Comment by hmf** [comment]
> 2.9.3-SNAPSHOT

You mean 3.9.3-SNAPSHOT :-)

**Comment by SethTisue** [comment]
I pushed a v3.9.2 tag just now

**Comment by SethTisue** [comment]
> Also the version on master should be 2.9.3-SNAPSHOT

I'd merge a PR that updated that appropriately, if it's still needed

**Comment by francisdb** [comment]
see #256 for that version change pr
