### ISSUE TITLE
Missing 3.9.2 jars for Scala 2.11

### ISSUE THREAD

**Issue by Atry** [lightbend/scala-logging#160]
https://repo1.maven.org/maven2/com/typesafe/scala-logging/scala-logging_2.11/3.9.2/ - 404 Not Found

 https://repo1.maven.org/maven2/com/typesafe/scala-logging/scala-logging_2.12/3.9.2/ - OK

**Comment by dejan2609** [comment]
@analytically can you please help us ?

**Comment by analytically** [comment]
I've published scala-logging_2.11-3.9.2

**Comment by dejan2609** [comment]
That was fast, thank you @analytically 👍
