### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by SethTisue** [lightbend/scala-logging#269]
would a volunteer like to attempt to add Scala 3 to the crossbuild?

**Comment by SethTisue** [comment]
oh haha wait this was actually done already, sorry, I got confused

so the next time we publish (work on that is underway at #225), that will include 3.0.0-RC1

**Comment by SethTisue** [comment]
the work was done by @amumurst in #227

**Comment by SethTisue** [comment]
Note that it would be awesome if a volunteer added this library to the Scala 3 community build.

**Comment by tomasherman** [comment]
I can help with that but i only see `scala 2 community build` here https://github.com/scala/community-build ... not sure where scala3 lives 🤔

**Comment by SethTisue** [comment]
@tomasherman here's the info: https://github.com/lampepfl/dotty/blob/master/community-build/README.md

**Comment by SethTisue** [comment]
3.9.3 is released for Scala 3.0.0-RC1! https://repo1.maven.org/maven2/com/typesafe/scala-logging/scala-logging_3.0.0-RC1/3.9.3/

**Comment by gregghz** [comment]
@SethTisue when can we expect a release for RC2?

**Comment by SethTisue** [comment]
@analytically is doing releases now (though I'm available to help if needed)

**Comment by sfxcode** [comment]
@analytically can you speed up the release with scala 3 version please - scala-logging is needed for me to do a scala 3 transition for my projects. THX

**Comment by SethTisue** [comment]
keeping open until publishing has happened

**Comment by icyrockcom** [comment]
Are code changes required or is this just pushing a new version out that's the same as 3.0-RC1?

**Comment by amumurst** [comment]
Changes needed are already merged in https://github.com/lightbend/scala-logging/pull/281. So as far as I know it`s just waiting for @analytically to have time to cut a release.

**Comment by otto-dev** [comment]
While I'm waiting / hoping for a published Scala 3.0.0 artifact, for my private project I'm doing `sbt ++3.0.0 publishLocal` and then using the locally published snapshot artifact. Of course this is a short-term crutch and only works if all your development happens on a single machine.

**Comment by otto-dev** [comment]
For private projects developed on a single machine, you can run `sbt ++3.0.0 publishLocal` in this repo and then use the local artifact for now, e.g. `"com.typesafe.scala-logging" % "scala-logging_3" % "3.9.3+16-8ff9473c-SNAPSHOT"`.

This is of course not sustainable long-term, but helps if you want to get going while waiting for the official release.

**Comment by adamw** [comment]
We'd be happy to help if there's anything left that is needed to be done before releasing for 3.0 :)

**Comment by amumurst** [comment]
@adamw As far as I know we only need to get hold of someone who knows how to release and has the priveleges to do so. 
(Also sidenote if you have looked at scala 3 macros I guess noone really looked at the stuff I did in https://github.com/lightbend/scala-logging/pull/227 to get scala 3 to compile and test, so it might not be optimal) :)

**Comment by analytically** [comment]
I'll get a release out today.

**Comment by analytically** [comment]
I'm seeing "Could not authorize build request" for this repo, according to Travis CI docs: "usually means that the account’s subscription expired or that it ran out of trial builds.", @SethTisue I don't have access to the Lightbend Travis CI console, could you check?

**Comment by SethTisue** [comment]
@analytically I'm having the same problem over at https://github.com/lightbend/mima/pull/643 — I'm pursuing it with Lightbend IT

**Comment by analytically** [comment]
I'm manually publishing 3.9.4 currently.

**Comment by adamw** [comment]
@amumurst I didn't read the code thoroughly, but `inline`s with quotes & splices in the implementation is what I'd expect to see there :) So looks good, especially if it works ;)

@analytically Thanks!

**Comment by analytically** [comment]
https://search.maven.org/artifact/com.typesafe.scala-logging/scala-logging_3/3.9.4/bundle

**Comment by adamw** [comment]
Works, thanks again!

**Comment by SethTisue** [comment]
(I'll continue to pursue the Travis-CI issue.)

**Comment by SethTisue** [comment]
Travis-CI is working again.
