### ISSUE TITLE
Ease parallel support of scala 2.10 and scala 2.11

### ISSUE THREAD

**Issue by tarmath** [lightbend/scala-logging#30]
We have a few generic libraries that we use across a variety of projects that makes extensive usage of scalalogging. As it turns out, we need to migrate to scala 2.11 in some projects while some others will stay behind for a few months. 

I was able to support both scala versions with no code changes at all, except for scalalogging. I minimized these changes to one file where I simply hide the diverging import. This is how it looks:

with scala 2.10 (scalalogging):

```
package com.tarmath.utils.logging
import com.typesafe.scalalogging.slf4j.{Logging => ScalaLogging}
trait Logging extends ScalaLogging
```

with scala 2.11 (scala-logging):

```
package com.tarmath.utils.logging
import com.typesafe.scalalogging.{LazyLogging => ScalaLogging}
trait Logging extends ScalaLogging
```

However, this needs to be replicated into several other libraries, and complicates our builds quite a bit. We are thus hoping that perhaps this tiny interface could be added directly to scalalogging (the older package) so as to allow the exact same import as what the newer scala-logging library requires. 

This could help other users of this library who are looking at upgrading and may need to support both versions for a while?

Otherwise, we'll proceed to add this hack everywhere and change our build processes.

Thanks!

**Comment by jlandahl** [comment]
+1

**Comment by tarmath** [comment]
closing this since everyone obviously moved on since
