### ISSUE TITLE
missing 3.6.0, 3.7.0, 3.7.1 and 3.7.2 tag on GitHub

### ISSUE THREAD

**Issue by xuwei-k** [lightbend/scala-logging#92]
https://github.com/typesafehub/scala-logging/tags

![2017-07-31 14 59 50](https://user-images.githubusercontent.com/389787/28764541-ee17c7b4-7600-11e7-809e-77a5b56def4e.png)

<hr />

http://repo1.maven.org/maven2/com/typesafe/scala-logging/scala-logging_2.12/

![2017-07-31 15 00 03](https://user-images.githubusercontent.com/389787/28764550-f5e56de8-7600-11e7-9e37-b96ebe47a148.png)

@analytically

**Comment by SethTisue** [comment]
seems unlikely anyone is still interested
