### ISSUE TITLE
No way to check logging level and avoid large-scale work outside of the macro.

### ISSUE THREAD

**Issue by ekmett-da** [lightbend/scala-logging#98]
With the logger using macros you can get it to inline any _one_ call to, say, `logger.info(message)`.

But if you have something that is logging with a for loop it'd be nice to be able to skip the entire loop if we're not logging at a high enough level.

The current API does not seem to expose enough functionality to be able to do so.

Example:

```scala
logger.info("UNMATCHED at " + now.toString)
something foreach (c => logger.info( c.id.substring(0,5) + " " + c.transactionId))
logger.info("---------------------------")
```

I don't see a way to avoid performing the loop when the log level is set to ignore info messages.

**Comment by DavidGregory084** [comment]
It's a bit gross, but you could do
```scala
if (logger.underlying.isInfoEnabled)
  something foreach (c => logger.info( c.id.substring(0,5) + " " + c.transactionId))

**Comment by analytically** [comment]
In 3.9.0 you now have `whenDebugEnabled` etc.
